### ISSUE TITLE
write_label ignores filepath parameter

### ISSUE THREAD

**Issue by AndrewAnnex** [SETI/rms-vicar#12]
the function `write_label` in VicarLabel ignores the user provided filepath parameter:
https://github.com/SETI/rms-vicar/blob/255c9916f20d3c124db54033b9059bf74dfb03f9/vicar/vicarlabel.py#L1150-L1158

now that first read at snippet may be important to do from the original file, but this function should actually write bits to whatever filepath parameter is provided. It may also be useful to have the ability to write labels that exist purely in memory also so the label size may need to be computed without the snippet if the filepath points to a file that does not exist on disk yet.

**Comment by markshowalter** [comment]
This was just a typo and I'll fix.
