### ISSUE TITLE
Clean up extra attributes in help()

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-vicar#5]
When you run `help(vicar)` there are extra, internal, attributes visible that should be hidden from the user.

**Comment by markshowalter** [comment]
This comment appears to refer to a different repo.

**Comment by rfrenchseti** [comment]
Sorry, cut-and-paste error. I think we still want these to be hidden though:

```
PACKAGE CONTENTS
    _LABEL_GRAMMAR
    _version
```
